default_contract_addresses:
  custody: "0x6F71a38d919ad713D0AfE0eB712b95064Fc2616f"
  adjudicator: "0x14980dF216722f14c42CA7357b06dEa7eB408b10"

blockchains:
- name: ethereum
  id: 1
  contract_addresses:
    balance_checker: "0xb1f8e55c7f64d203c1400b9d8555d050f94adf39"
- name: flare
  id: 14
  disabled: true
  contract_addresses:
    balance_checker: "0x714698e8fe7896bb84A46c0705944c4a48580819"
- name: bsc
  id: 56
  contract_addresses:
    balance_checker: "0x2352c63A83f9Fd126af8676146721Fa00924d7e4"
- name: polygon
  id: 137
  contract_addresses:
    balance_checker: "0x2352c63A83f9Fd126af8676146721Fa00924d7e4"
- name: world_chain
  id: 480
  contract_addresses:
    balance_checker: "0x6D3B5EFa1f81f65037cD842F48E44BcBCa48CBEF"
- name: flow
  id: 747
  disabled: true
  contract_addresses:
    balance_checker: "0xa3f2f64455c9f8D68d9dCAeC2605D64680FaF898"
- name: ronin
  id: 2020
  disabled: true
  contract_addresses:
    balance_checker: "0x714698e8fe7896bb84A46c0705944c4a48580819"
- name: kaia
  id: 8217
  contract_addresses:
    balance_checker: "0x714698e8fe7896bb84A46c0705944c4a48580819"
- name: base
  id: 8453
  contract_addresses:
    custody: "0x490fb189DdE3a01B00be9BA5F41e3447FbC838b6"
    adjudicator: "0x7de4A0736Cf5740fD3Ca2F2e9cc85c9AC223eF0C"
    balance_checker: "0x3ba5A41eA17fd4950a641a057dC0bEb8E8ff1521"
- name: linea
  id: 59144
  contract_addresses:
    balance_checker: "0xF62e6a41561b3650a69Bb03199C735e3E3328c0D"
- name: xrpl_evm
  id: 1440000
  contract_addresses:
    balance_checker: "0x714698e8fe7896bb84A46c0705944c4a48580819"
