config:
  database:
    password: ref+tfstategs://terraform-state-deploy/gke-uat-postgresql-admin/default.tfstate/output.postgresql_user_passwords["clearnet_prod_admin"]
  secretEnvs:
    BROKER_PRIVATE_KEY: ref+gcpsecrets://ynet-stage/clearnet-prod-broker-private-key?version=latest
    ETHEREUM_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-eth-mainnet-blockchain-rpc?version=latest
    FLARE_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-flare-blockchain-rpc?version=latest
    BSC_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-bsc-blockchain-rpc?version=latest
    POLYGON_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-polygon-blockchain-rpc?version=latest
    WORLD_CHAIN_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-worldchain-blockchain-rpc?version=latest
    FLOW_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-flow-blockchain-rpc?version=latest
    RONIN_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-ronin-blockchain-rpc?version=latest
    KAIA_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-kaia-blockchain-rpc?version=latest
    BASE_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-base-blockchain-rpc?version=latest
    LINEA_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-linea-mainnet-blockchain-rpc?version=latest
    XRPL_EVM_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-prod-xrpl-evm-mainnet-blockchain-rpc?version=latest
