assets:
  - name: "ytest.USD"
    symbol: "ytest.usd"
    tokens:
      - blockchain_id: 11155111
        address: "0xDB9F293e3898c9E5536A3be1b0C56c89d2b32DEb"
        decimals: 6
      - blockchain_id: 59141
        address: "0xDB9F293e3898c9E5536A3be1b0C56c89d2b32DEb"
        decimals: 6
      - blockchain_id: 80002
        address: "0xDB9F293e3898c9E5536A3be1b0C56c89d2b32DEb"
        decimals: 6
      - blockchain_id: 84532
        address: "0xDB9F293e3898c9E5536A3be1b0C56c89d2b32DEb"
        decimals: 6
      - blockchain_id: 1449000
        disabled: true
        address: "0xDB9F293e3898c9E5536A3be1b0C56c89d2b32DEb"
        decimals: 6
  - name: Ether
    symbol: eth
    tokens:
      - blockchain_id: 0
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
