apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clearnode.common.fullname" . }}-config
  labels:
    {{- include "clearnode.common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
  blockchains.yaml: |-
{{ .Values.config.blockchains | indent 4 }}
  assets.yaml: |-
{{ .Values.config.assets | indent 4 }}
