default_contract_addresses:
  custody: "0x019B65A265EB3363822f2752141b3dF16131b262"
  adjudicator: "0x7c7ccbc98469190849BCC6c926307794fDfB11F2"

blockchains:
- name: polygon_amoy
  id: 80002
  contract_addresses:
    balance_checker: "0x9d1E88627884e066B81A02d69BCB2437a520534C"
- name: base_sepolia
  id: 84532
  contract_addresses:
    balance_checker: "0x33e57a8900882B8D5A038eC3Aa844c19Acfc539A"
- name: ethereum_sepolia
  id: 11155111
  disabled: true
  contract_addresses:
    balance_checker: "0x86700f6bc63a42ee645e204b361d7c0f643c111b"
- name: linea_sepolia
  id: 59141
  disabled: true
  contract_addresses:
    balance_checker: "0x424A079B89571a515Fd6fe0ba614060D5Fd8E16A"
- name: xrpl_evm_testnet
  id: 1449000
  disabled: true
  contract_addresses:
    custody: "0x442f5544983eA73ED75FbDD252bc03842D185284"
    adjudicator: "0xBa28DC8F50d076Df76fF9959f31A320686faa373"
    balance_checker: "0x714698e8fe7896bb84A46c0705944c4a48580819"
  block_step: 499
