assets:
  - name: "ETH"
    symbol: "eth"
    tokens:
      - blockchain_id: 84532
        address: "0x0000000000000000000000000000000000000000"
        decimals: 18
  - name: "USDC"
    symbol: "usdc"
    tokens:
      - blockchain_id: 84532
        address: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
        decimals: 6
